// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"devcloud/ent/predicate"
	"devcloud/ent/resource"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ResourceUpdate is the builder for updating Resource entities.
type ResourceUpdate struct {
	config
	hooks    []Hook
	mutation *ResourceMutation
}

// Where appends a list predicates to the ResourceUpdate builder.
func (_u *ResourceUpdate) Where(ps ...predicate.Resource) *ResourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ResourceUpdate) SetUserID(v int) *ResourceUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableUserID(v *int) *ResourceUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ResourceUpdate) AddUserID(v int) *ResourceUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ResourceUpdate) SetName(v string) *ResourceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableName(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ResourceUpdate) SetProvider(v resource.Provider) *ResourceUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableProvider(v *resource.Provider) *ResourceUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetImage sets the "image" field.
func (_u *ResourceUpdate) SetImage(v string) *ResourceUpdate {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableImage(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// SetRuntimeID sets the "runtime_id" field.
func (_u *ResourceUpdate) SetRuntimeID(v string) *ResourceUpdate {
	_u.mutation.SetRuntimeID(v)
	return _u
}

// SetNillableRuntimeID sets the "runtime_id" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableRuntimeID(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetRuntimeID(*v)
	}
	return _u
}

// ClearRuntimeID clears the value of the "runtime_id" field.
func (_u *ResourceUpdate) ClearRuntimeID() *ResourceUpdate {
	_u.mutation.ClearRuntimeID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResourceUpdate) SetStatus(v resource.Status) *ResourceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableStatus(v *resource.Status) *ResourceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *ResourceUpdate) SetConfig(v map[string]interface{}) *ResourceUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *ResourceUpdate) ClearConfig() *ResourceUpdate {
	_u.mutation.ClearConfig()
	return _u
}

// SetCredential sets the "credential" field.
func (_u *ResourceUpdate) SetCredential(v string) *ResourceUpdate {
	_u.mutation.SetCredential(v)
	return _u
}

// SetNillableCredential sets the "credential" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableCredential(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetCredential(*v)
	}
	return _u
}

// ClearCredential clears the value of the "credential" field.
func (_u *ResourceUpdate) ClearCredential() *ResourceUpdate {
	_u.mutation.ClearCredential()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ResourceUpdate) SetCreatedAt(v time.Time) *ResourceUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableCreatedAt(v *time.Time) *ResourceUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResourceUpdate) SetUpdatedAt(v time.Time) *ResourceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ResourceUpdate) SetDeletedAt(v time.Time) *ResourceUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableDeletedAt(v *time.Time) *ResourceUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ResourceUpdate) ClearDeletedAt() *ResourceUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the ResourceMutation object of the builder.
func (_u *ResourceUpdate) Mutation() *ResourceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResourceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResourceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := resource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Resource.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := resource.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "Resource.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Image(); ok {
		if err := resource.ImageValidator(v); err != nil {
			return &ValidationError{Name: "image", err: fmt.Errorf(`ent: validator failed for field "Resource.image": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RuntimeID(); ok {
		if err := resource.RuntimeIDValidator(v); err != nil {
			return &ValidationError{Name: "runtime_id", err: fmt.Errorf(`ent: validator failed for field "Resource.runtime_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := resource.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Resource.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ResourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resource.Table, resource.Columns, sqlgraph.NewFieldSpec(resource.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(resource.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(resource.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(resource.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(resource.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(resource.FieldImage, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuntimeID(); ok {
		_spec.SetField(resource.FieldRuntimeID, field.TypeString, value)
	}
	if _u.mutation.RuntimeIDCleared() {
		_spec.ClearField(resource.FieldRuntimeID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(resource.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(resource.FieldConfig, field.TypeJSON, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(resource.FieldConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.Credential(); ok {
		_spec.SetField(resource.FieldCredential, field.TypeString, value)
	}
	if _u.mutation.CredentialCleared() {
		_spec.ClearField(resource.FieldCredential, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(resource.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resource.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(resource.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(resource.FieldDeletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResourceUpdateOne is the builder for updating a single Resource entity.
type ResourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResourceMutation
}

// SetUserID sets the "user_id" field.
func (_u *ResourceUpdateOne) SetUserID(v int) *ResourceUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableUserID(v *int) *ResourceUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ResourceUpdateOne) AddUserID(v int) *ResourceUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ResourceUpdateOne) SetName(v string) *ResourceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableName(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ResourceUpdateOne) SetProvider(v resource.Provider) *ResourceUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableProvider(v *resource.Provider) *ResourceUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetImage sets the "image" field.
func (_u *ResourceUpdateOne) SetImage(v string) *ResourceUpdateOne {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableImage(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// SetRuntimeID sets the "runtime_id" field.
func (_u *ResourceUpdateOne) SetRuntimeID(v string) *ResourceUpdateOne {
	_u.mutation.SetRuntimeID(v)
	return _u
}

// SetNillableRuntimeID sets the "runtime_id" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableRuntimeID(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetRuntimeID(*v)
	}
	return _u
}

// ClearRuntimeID clears the value of the "runtime_id" field.
func (_u *ResourceUpdateOne) ClearRuntimeID() *ResourceUpdateOne {
	_u.mutation.ClearRuntimeID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResourceUpdateOne) SetStatus(v resource.Status) *ResourceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableStatus(v *resource.Status) *ResourceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *ResourceUpdateOne) SetConfig(v map[string]interface{}) *ResourceUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *ResourceUpdateOne) ClearConfig() *ResourceUpdateOne {
	_u.mutation.ClearConfig()
	return _u
}

// SetCredential sets the "credential" field.
func (_u *ResourceUpdateOne) SetCredential(v string) *ResourceUpdateOne {
	_u.mutation.SetCredential(v)
	return _u
}

// SetNillableCredential sets the "credential" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableCredential(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetCredential(*v)
	}
	return _u
}

// ClearCredential clears the value of the "credential" field.
func (_u *ResourceUpdateOne) ClearCredential() *ResourceUpdateOne {
	_u.mutation.ClearCredential()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ResourceUpdateOne) SetCreatedAt(v time.Time) *ResourceUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableCreatedAt(v *time.Time) *ResourceUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResourceUpdateOne) SetUpdatedAt(v time.Time) *ResourceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ResourceUpdateOne) SetDeletedAt(v time.Time) *ResourceUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableDeletedAt(v *time.Time) *ResourceUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ResourceUpdateOne) ClearDeletedAt() *ResourceUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the ResourceMutation object of the builder.
func (_u *ResourceUpdateOne) Mutation() *ResourceMutation {
	return _u.mutation
}

// Where appends a list predicates to the ResourceUpdate builder.
func (_u *ResourceUpdateOne) Where(ps ...predicate.Resource) *ResourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResourceUpdateOne) Select(field string, fields ...string) *ResourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Resource entity.
func (_u *ResourceUpdateOne) Save(ctx context.Context) (*Resource, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceUpdateOne) SaveX(ctx context.Context) *Resource {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResourceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := resource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Resource.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := resource.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "Resource.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Image(); ok {
		if err := resource.ImageValidator(v); err != nil {
			return &ValidationError{Name: "image", err: fmt.Errorf(`ent: validator failed for field "Resource.image": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RuntimeID(); ok {
		if err := resource.RuntimeIDValidator(v); err != nil {
			return &ValidationError{Name: "runtime_id", err: fmt.Errorf(`ent: validator failed for field "Resource.runtime_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := resource.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Resource.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ResourceUpdateOne) sqlSave(ctx context.Context) (_node *Resource, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resource.Table, resource.Columns, sqlgraph.NewFieldSpec(resource.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Resource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resource.FieldID)
		for _, f := range fields {
			if !resource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != resource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(resource.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(resource.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(resource.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(resource.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(resource.FieldImage, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuntimeID(); ok {
		_spec.SetField(resource.FieldRuntimeID, field.TypeString, value)
	}
	if _u.mutation.RuntimeIDCleared() {
		_spec.ClearField(resource.FieldRuntimeID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(resource.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(resource.FieldConfig, field.TypeJSON, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(resource.FieldConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.Credential(); ok {
		_spec.SetField(resource.FieldCredential, field.TypeString, value)
	}
	if _u.mutation.CredentialCleared() {
		_spec.ClearField(resource.FieldCredential, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(resource.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resource.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(resource.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(resource.FieldDeletedAt, field.TypeTime)
	}
	_node = &Resource{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
