// Code generated by ent, DO NOT EDIT.

package ent

import (
	"devcloud/ent/refreshtoken"
	"devcloud/ent/resource"
	"devcloud/ent/schema"
	"devcloud/ent/task"
	"devcloud/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	refreshtokenFields := schema.RefreshToken{}.Fields()
	_ = refreshtokenFields
	// refreshtokenDescTokenHash is the schema descriptor for token_hash field.
	refreshtokenDescTokenHash := refreshtokenFields[1].Descriptor()
	// refreshtoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	refreshtoken.TokenHashValidator = refreshtokenDescTokenHash.Validators[0].(func(string) error)
	// refreshtokenDescCreatedAt is the schema descriptor for created_at field.
	refreshtokenDescCreatedAt := refreshtokenFields[3].Descriptor()
	// refreshtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	refreshtoken.DefaultCreatedAt = refreshtokenDescCreatedAt.Default.(func() time.Time)
	resourceFields := schema.Resource{}.Fields()
	_ = resourceFields
	// resourceDescName is the schema descriptor for name field.
	resourceDescName := resourceFields[1].Descriptor()
	// resource.NameValidator is a validator for the "name" field. It is called by the builders before save.
	resource.NameValidator = resourceDescName.Validators[0].(func(string) error)
	// resourceDescImage is the schema descriptor for image field.
	resourceDescImage := resourceFields[3].Descriptor()
	// resource.ImageValidator is a validator for the "image" field. It is called by the builders before save.
	resource.ImageValidator = resourceDescImage.Validators[0].(func(string) error)
	// resourceDescRuntimeID is the schema descriptor for runtime_id field.
	resourceDescRuntimeID := resourceFields[4].Descriptor()
	// resource.RuntimeIDValidator is a validator for the "runtime_id" field. It is called by the builders before save.
	resource.RuntimeIDValidator = resourceDescRuntimeID.Validators[0].(func(string) error)
	// resourceDescCreatedAt is the schema descriptor for created_at field.
	resourceDescCreatedAt := resourceFields[8].Descriptor()
	// resource.DefaultCreatedAt holds the default value on creation for the created_at field.
	resource.DefaultCreatedAt = resourceDescCreatedAt.Default.(func() time.Time)
	// resourceDescUpdatedAt is the schema descriptor for updated_at field.
	resourceDescUpdatedAt := resourceFields[9].Descriptor()
	// resource.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	resource.DefaultUpdatedAt = resourceDescUpdatedAt.Default.(func() time.Time)
	// resource.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	resource.UpdateDefaultUpdatedAt = resourceDescUpdatedAt.UpdateDefault.(func() time.Time)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescAttempts is the schema descriptor for attempts field.
	taskDescAttempts := taskFields[4].Descriptor()
	// task.DefaultAttempts holds the default value on creation for the attempts field.
	task.DefaultAttempts = taskDescAttempts.Default.(int)
	// taskDescMaxAttempts is the schema descriptor for max_attempts field.
	taskDescMaxAttempts := taskFields[5].Descriptor()
	// task.DefaultMaxAttempts holds the default value on creation for the max_attempts field.
	task.DefaultMaxAttempts = taskDescMaxAttempts.Default.(int)
	// taskDescNextRunAt is the schema descriptor for next_run_at field.
	taskDescNextRunAt := taskFields[6].Descriptor()
	// task.DefaultNextRunAt holds the default value on creation for the next_run_at field.
	task.DefaultNextRunAt = taskDescNextRunAt.Default.(time.Time)
	// taskDescWorkerID is the schema descriptor for worker_id field.
	taskDescWorkerID := taskFields[9].Descriptor()
	// task.WorkerIDValidator is a validator for the "worker_id" field. It is called by the builders before save.
	task.WorkerIDValidator = taskDescWorkerID.Validators[0].(func(string) error)
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskFields[13].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskFields[14].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[1].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescNickname is the schema descriptor for nickname field.
	userDescNickname := userFields[2].Descriptor()
	// user.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	user.NicknameValidator = userDescNickname.Validators[0].(func(string) error)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[3].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(int8)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
