// Code generated by ent, DO NOT EDIT.

package ent

import (
	"devcloud/ent/schema"
	"devcloud/ent/token"
	"devcloud/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	tokenFields := schema.Token{}.Fields()
	_ = tokenFields
	// tokenDescUID is the schema descriptor for uid field.
	tokenDescUID := tokenFields[0].Descriptor()
	// token.UIDValidator is a validator for the "uid" field. It is called by the builders before save.
	token.UIDValidator = tokenDescUID.Validators[0].(func(int) error)
	// tokenDescToken is the schema descriptor for token field.
	tokenDescToken := tokenFields[1].Descriptor()
	// token.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	token.TokenValidator = tokenDescToken.Validators[0].(func(string) error)
	// tokenDescUserAgent is the schema descriptor for user_agent field.
	tokenDescUserAgent := tokenFields[2].Descriptor()
	// token.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	token.UserAgentValidator = tokenDescUserAgent.Validators[0].(func(string) error)
	// tokenDescCeratedAt is the schema descriptor for cerated_at field.
	tokenDescCeratedAt := tokenFields[4].Descriptor()
	// token.DefaultCeratedAt holds the default value on creation for the cerated_at field.
	token.DefaultCeratedAt = tokenDescCeratedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[1].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescNickname is the schema descriptor for nickname field.
	userDescNickname := userFields[2].Descriptor()
	// user.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	user.NicknameValidator = userDescNickname.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}
