// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"devcloud/ent/predicate"
	"devcloud/ent/task"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskUpdate is the builder for updating Task entities.
type TaskUpdate struct {
	config
	hooks    []Hook
	mutation *TaskMutation
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdate) Where(ps ...predicate.Task) *TaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TaskUpdate) SetUserID(v int) *TaskUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableUserID(v *int) *TaskUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *TaskUpdate) AddUserID(v int) *TaskUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *TaskUpdate) SetResourceID(v int) *TaskUpdate {
	_u.mutation.ResetResourceID()
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableResourceID(v *int) *TaskUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// AddResourceID adds value to the "resource_id" field.
func (_u *TaskUpdate) AddResourceID(v int) *TaskUpdate {
	_u.mutation.AddResourceID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *TaskUpdate) SetType(v task.Type) *TaskUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableType(v *task.Type) *TaskUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskUpdate) SetStatus(v task.Status) *TaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableStatus(v *task.Status) *TaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *TaskUpdate) SetAttempts(v int) *TaskUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableAttempts(v *int) *TaskUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *TaskUpdate) AddAttempts(v int) *TaskUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetMaxAttempts sets the "max_attempts" field.
func (_u *TaskUpdate) SetMaxAttempts(v int) *TaskUpdate {
	_u.mutation.ResetMaxAttempts()
	_u.mutation.SetMaxAttempts(v)
	return _u
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableMaxAttempts(v *int) *TaskUpdate {
	if v != nil {
		_u.SetMaxAttempts(*v)
	}
	return _u
}

// AddMaxAttempts adds value to the "max_attempts" field.
func (_u *TaskUpdate) AddMaxAttempts(v int) *TaskUpdate {
	_u.mutation.AddMaxAttempts(v)
	return _u
}

// SetNextRunAt sets the "next_run_at" field.
func (_u *TaskUpdate) SetNextRunAt(v time.Time) *TaskUpdate {
	_u.mutation.SetNextRunAt(v)
	return _u
}

// SetNillableNextRunAt sets the "next_run_at" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableNextRunAt(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetNextRunAt(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *TaskUpdate) SetPayload(v map[string]interface{}) *TaskUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *TaskUpdate) ClearPayload() *TaskUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *TaskUpdate) SetErrorMessage(v string) *TaskUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableErrorMessage(v *string) *TaskUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *TaskUpdate) ClearErrorMessage() *TaskUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetWorkerID sets the "worker_id" field.
func (_u *TaskUpdate) SetWorkerID(v string) *TaskUpdate {
	_u.mutation.SetWorkerID(v)
	return _u
}

// SetNillableWorkerID sets the "worker_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableWorkerID(v *string) *TaskUpdate {
	if v != nil {
		_u.SetWorkerID(*v)
	}
	return _u
}

// ClearWorkerID clears the value of the "worker_id" field.
func (_u *TaskUpdate) ClearWorkerID() *TaskUpdate {
	_u.mutation.ClearWorkerID()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *TaskUpdate) SetStartedAt(v time.Time) *TaskUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableStartedAt(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *TaskUpdate) ClearStartedAt() *TaskUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (_u *TaskUpdate) SetHeartbeatAt(v time.Time) *TaskUpdate {
	_u.mutation.SetHeartbeatAt(v)
	return _u
}

// SetNillableHeartbeatAt sets the "heartbeat_at" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableHeartbeatAt(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetHeartbeatAt(*v)
	}
	return _u
}

// ClearHeartbeatAt clears the value of the "heartbeat_at" field.
func (_u *TaskUpdate) ClearHeartbeatAt() *TaskUpdate {
	_u.mutation.ClearHeartbeatAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *TaskUpdate) SetFinishedAt(v time.Time) *TaskUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableFinishedAt(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *TaskUpdate) ClearFinishedAt() *TaskUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TaskUpdate) SetCreatedAt(v time.Time) *TaskUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableCreatedAt(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskUpdate) SetUpdatedAt(v time.Time) *TaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdate) Mutation() *TaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := task.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Task.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := task.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Task.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WorkerID(); ok {
		if err := task.WorkerIDValidator(v); err != nil {
			return &ValidationError{Name: "worker_id", err: fmt.Errorf(`ent: validator failed for field "Task.worker_id": %w`, err)}
		}
	}
	return nil
}

func (_u *TaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(task.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(task.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(task.FieldResourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResourceID(); ok {
		_spec.AddField(task.FieldResourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(task.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(task.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(task.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxAttempts(); ok {
		_spec.SetField(task.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxAttempts(); ok {
		_spec.AddField(task.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextRunAt(); ok {
		_spec.SetField(task.FieldNextRunAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(task.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(task.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(task.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(task.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.WorkerID(); ok {
		_spec.SetField(task.FieldWorkerID, field.TypeString, value)
	}
	if _u.mutation.WorkerIDCleared() {
		_spec.ClearField(task.FieldWorkerID, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(task.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(task.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HeartbeatAt(); ok {
		_spec.SetField(task.FieldHeartbeatAt, field.TypeTime, value)
	}
	if _u.mutation.HeartbeatAtCleared() {
		_spec.ClearField(task.FieldHeartbeatAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(task.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(task.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(task.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskUpdateOne is the builder for updating a single Task entity.
type TaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskMutation
}

// SetUserID sets the "user_id" field.
func (_u *TaskUpdateOne) SetUserID(v int) *TaskUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableUserID(v *int) *TaskUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *TaskUpdateOne) AddUserID(v int) *TaskUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *TaskUpdateOne) SetResourceID(v int) *TaskUpdateOne {
	_u.mutation.ResetResourceID()
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableResourceID(v *int) *TaskUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// AddResourceID adds value to the "resource_id" field.
func (_u *TaskUpdateOne) AddResourceID(v int) *TaskUpdateOne {
	_u.mutation.AddResourceID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *TaskUpdateOne) SetType(v task.Type) *TaskUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableType(v *task.Type) *TaskUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskUpdateOne) SetStatus(v task.Status) *TaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableStatus(v *task.Status) *TaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *TaskUpdateOne) SetAttempts(v int) *TaskUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableAttempts(v *int) *TaskUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *TaskUpdateOne) AddAttempts(v int) *TaskUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetMaxAttempts sets the "max_attempts" field.
func (_u *TaskUpdateOne) SetMaxAttempts(v int) *TaskUpdateOne {
	_u.mutation.ResetMaxAttempts()
	_u.mutation.SetMaxAttempts(v)
	return _u
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableMaxAttempts(v *int) *TaskUpdateOne {
	if v != nil {
		_u.SetMaxAttempts(*v)
	}
	return _u
}

// AddMaxAttempts adds value to the "max_attempts" field.
func (_u *TaskUpdateOne) AddMaxAttempts(v int) *TaskUpdateOne {
	_u.mutation.AddMaxAttempts(v)
	return _u
}

// SetNextRunAt sets the "next_run_at" field.
func (_u *TaskUpdateOne) SetNextRunAt(v time.Time) *TaskUpdateOne {
	_u.mutation.SetNextRunAt(v)
	return _u
}

// SetNillableNextRunAt sets the "next_run_at" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableNextRunAt(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetNextRunAt(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *TaskUpdateOne) SetPayload(v map[string]interface{}) *TaskUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *TaskUpdateOne) ClearPayload() *TaskUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *TaskUpdateOne) SetErrorMessage(v string) *TaskUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableErrorMessage(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *TaskUpdateOne) ClearErrorMessage() *TaskUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetWorkerID sets the "worker_id" field.
func (_u *TaskUpdateOne) SetWorkerID(v string) *TaskUpdateOne {
	_u.mutation.SetWorkerID(v)
	return _u
}

// SetNillableWorkerID sets the "worker_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableWorkerID(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetWorkerID(*v)
	}
	return _u
}

// ClearWorkerID clears the value of the "worker_id" field.
func (_u *TaskUpdateOne) ClearWorkerID() *TaskUpdateOne {
	_u.mutation.ClearWorkerID()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *TaskUpdateOne) SetStartedAt(v time.Time) *TaskUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableStartedAt(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *TaskUpdateOne) ClearStartedAt() *TaskUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (_u *TaskUpdateOne) SetHeartbeatAt(v time.Time) *TaskUpdateOne {
	_u.mutation.SetHeartbeatAt(v)
	return _u
}

// SetNillableHeartbeatAt sets the "heartbeat_at" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableHeartbeatAt(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetHeartbeatAt(*v)
	}
	return _u
}

// ClearHeartbeatAt clears the value of the "heartbeat_at" field.
func (_u *TaskUpdateOne) ClearHeartbeatAt() *TaskUpdateOne {
	_u.mutation.ClearHeartbeatAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *TaskUpdateOne) SetFinishedAt(v time.Time) *TaskUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableFinishedAt(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *TaskUpdateOne) ClearFinishedAt() *TaskUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TaskUpdateOne) SetCreatedAt(v time.Time) *TaskUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableCreatedAt(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskUpdateOne) SetUpdatedAt(v time.Time) *TaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdateOne) Mutation() *TaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdateOne) Where(ps ...predicate.Task) *TaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskUpdateOne) Select(field string, fields ...string) *TaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Task entity.
func (_u *TaskUpdateOne) Save(ctx context.Context) (*Task, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdateOne) SaveX(ctx context.Context) *Task {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := task.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Task.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := task.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Task.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WorkerID(); ok {
		if err := task.WorkerIDValidator(v); err != nil {
			return &ValidationError{Name: "worker_id", err: fmt.Errorf(`ent: validator failed for field "Task.worker_id": %w`, err)}
		}
	}
	return nil
}

func (_u *TaskUpdateOne) sqlSave(ctx context.Context) (_node *Task, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Task.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, task.FieldID)
		for _, f := range fields {
			if !task.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != task.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(task.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(task.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(task.FieldResourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResourceID(); ok {
		_spec.AddField(task.FieldResourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(task.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(task.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(task.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxAttempts(); ok {
		_spec.SetField(task.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxAttempts(); ok {
		_spec.AddField(task.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextRunAt(); ok {
		_spec.SetField(task.FieldNextRunAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(task.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(task.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(task.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(task.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.WorkerID(); ok {
		_spec.SetField(task.FieldWorkerID, field.TypeString, value)
	}
	if _u.mutation.WorkerIDCleared() {
		_spec.ClearField(task.FieldWorkerID, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(task.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(task.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HeartbeatAt(); ok {
		_spec.SetField(task.FieldHeartbeatAt, field.TypeTime, value)
	}
	if _u.mutation.HeartbeatAtCleared() {
		_spec.ClearField(task.FieldHeartbeatAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(task.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(task.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(task.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Task{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
