// Code generated by ent, DO NOT EDIT.

package resource

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the resource type in the database.
	Label = "resource"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldImage holds the string denoting the image field in the database.
	FieldImage = "image"
	// FieldRuntimeID holds the string denoting the runtime_id field in the database.
	FieldRuntimeID = "runtime_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldConfig holds the string denoting the config field in the database.
	FieldConfig = "config"
	// FieldCredential holds the string denoting the credential field in the database.
	FieldCredential = "credential"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// Table holds the table name of the resource in the database.
	Table = "resources"
)

// Columns holds all SQL columns for resource fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldName,
	FieldProvider,
	FieldImage,
	FieldRuntimeID,
	FieldStatus,
	FieldConfig,
	FieldCredential,
	FieldErrorMessage,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// ImageValidator is a validator for the "image" field. It is called by the builders before save.
	ImageValidator func(string) error
	// RuntimeIDValidator is a validator for the "runtime_id" field. It is called by the builders before save.
	RuntimeIDValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Provider defines the type for the "provider" enum field.
type Provider string

// ProviderDocker is the default value of the Provider enum.
const DefaultProvider = ProviderDocker

// Provider values.
const (
	ProviderDocker Provider = "docker"
)

func (pr Provider) String() string {
	return string(pr)
}

// ProviderValidator is a validator for the "provider" field enum values. It is called by the builders before save.
func ProviderValidator(pr Provider) error {
	switch pr {
	case ProviderDocker:
		return nil
	default:
		return fmt.Errorf("resource: invalid enum value for provider field: %q", pr)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusCREATING is the default value of the Status enum.
const DefaultStatus = StatusCREATING

// Status values.
const (
	StatusCREATING   Status = "CREATING"
	StatusRUNNING    Status = "RUNNING"
	StatusSTOPPING   Status = "STOPPING"
	StatusSTOPPED    Status = "STOPPED"
	StatusSTARTING   Status = "STARTING"
	StatusRESTARTING Status = "RESTARTING"
	StatusREMOVING   Status = "REMOVING"
	StatusREMOVED    Status = "REMOVED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusCREATING, StatusRUNNING, StatusSTOPPING, StatusSTOPPED, StatusSTARTING, StatusRESTARTING, StatusREMOVING, StatusREMOVED:
		return nil
	default:
		return fmt.Errorf("resource: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Resource queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByImage orders the results by the image field.
func ByImage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImage, opts...).ToFunc()
}

// ByRuntimeID orders the results by the runtime_id field.
func ByRuntimeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuntimeID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCredential orders the results by the credential field.
func ByCredential(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCredential, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}
